'PROGRAM: impact.prg          Copyright (C) 2012 Alphametrics Co. Ltd.
'
' CAM Version 5.1
'
' dynamic multiplier analysis - impact report
'
' you can run this program to generate reports after
' running solm.prg (dynamic multiplier analysis)
'
' the program generates impact reports for variables
' that you list below in relation to the last shock
' scenario that has been generated by solm.prg or shock.prg
'
' the relevant workfile must be open before you execute
' this program and the reports generated are added
' to the workfile graphs and tables page
'
' 1. type a new list of variables or expressions below
'
' 2. run the program by typing   run impact
'
' updated: FC 11/04/2013
'
'==================================================================
' OPTIONS
'==================================================================

'--- replace the list of variables or expressions here

%impacton = "NU_US NE_US NLG_US LG_US CA$_US"
%graphs = "Yes"

'==================================================================
' PROCESSING
'==================================================================

mode quiet
tic
include "set.prg"
pageselect data
show sp_log
call pLog("IMPACT PROGRAM v1104")
!qgraph = @upper(@left(%graphs,1)) = "Y"
call pShockImpact(%impacton, 1, !qgraph)
call pEnd
