'PROGRAM: impact.prg          Copyright (C) 2012 Alphametrics Co. Ltd.
'
' CAM version 4.6
'
' dynamic multiplier analysis - impact report
'
' you can run this program to generate reports after
' running solm.prg (dynamic multiplier analysis)
'
' the program generates impact reports for variables
' that you list below in relation to the last shock
' scenario that has been generated by solm.prg
'
' the SOLM workfile must be open before you execute
' this program and the reports generated are appended
' to the output listing (sp_log)
'
' 1. type a new list of variables or expressions below
'
' 2. run the program by typing   run impact
'
' updated: NK 15/09/2010
'
'==================================================================
' OPTIONS
'==================================================================

'--- replace the list of variables or expressions here

%impacton = "NIM_US NAR_US NE_US HWP_US WP_US IAGO_US rxna_EU"
%graphs = "Yes"

'==================================================================
' PROCESSING
'==================================================================

mode quiet
tic
include "set.prg"
pageselect data
show sp_log
call pLog("IMPACT PROGRAM v1509")
!qgraph = @upper(@left(%graphs,1)) = "Y"
call pShockImpact(%impacton, 1, !qgraph)
call pEnd
