'PROGRAM: impact.prg     Copyright 2012,2015 Alphametrics Co., Ltd.
'
' CAM version 6.0 utility
'
' dynamic multiplier analysis - impact report
'
' you can run this program to generate reports after
' running solm.prg (dynamic multiplier analysis)
'
' the program generates impact reports for variables
' that you list below in relation to the last shock
' scenario that has been generated by solm.prg or shock.prg
'
' the relevant workfile must be open before you execute
' this program and the reports generated are added
' to the workfile graphs and tables page
'
' 1. type a new list of variables or expressions below
'
' 2. run the program by typing   run impact
'
' updated: FC 27/07/2012
'
'==================================================================
' OPTIONS
'==================================================================

'--- replace the list of variables or expressions here

%impacton = "tt_CN rxna_CN"
%graphs = "Yes"

'==================================================================
' PROCESSING
'==================================================================

mode quiet
tic
include "set.prg"
pageselect data
output(s) sp_log
show sp_log
call pLog("IMPACT PROGRAM v2707")
!qgraph = @upper(@left(%graphs,1)) = "Y"
call pShockImpact(%impacton, 1, !qgraph)
call pEnd
